//actions
export const CHANGE_FIRST_NAME = "CHANGE_FIRST_NAME";
export const CHANGE_MIDDLE_NAME = "CHANGE_MIDDLE_NAME";
export const CHANGE_LAST_NAME = "CHANGE_LAST_NAME";
export const CHANGE_TRADING_NAME = "CHANGE_TRADING_NAME";
export const CHANGE_TRADE_ACCNT_NAME = "CHANGE_TRADE_ACCNT_NAME";
export const CHANGE_ADDRESS = "CHANGE_ADDRESS";
export const UPDATE_CUSTOMER_LIST = "UPDATE_CUSTOMER_LIST";
export const GET_CUSTOMER_LIST = "GET_CUSTOMER_LIST";


//api URI
export const GET_CUSTOMER_URI = "/users/customer";
