//actions
export const CHANGE_FIRST_NAME = "CHANGE_FIRST_NAME";
export const CHANGE_MIDDLE_NAME = "CHANGE_MIDDLE_NAME";
export const CHANGE_LAST_NAME = "CHANGE_LAST_NAME";
export const CHANGE_TRADING_NAME = "CHANGE_TRADING_NAME";
export const CHANGE_TRADE_ACCNT_NAME = "CHANGE_TRADE_ACCNT_NAME";
export const CHANGE_ADDRESS = "CHANGE_ADDRESS";
export const CHANGE_COMPONENT_ADD = "CHANGE_COMPONENT_ADD";
export const CHANGE_COMPONENT_LIST = "CHANGE_COMPONENT_LIST";
export const CHANGE_COMPONENT_EDIT = "CHANGE_COMPONENT_EDIT";
export const CHANGE_LIST_PAGE = "CHANGE_LIST_PAGE";
export const EDIT_CUSTOMER = "EDIT_CUSTOMER";
export const UPDATE_AFTER_SEARCH = "UPDATE_AFTER_SEARCH";

export const UPDATE_CUSTOMER_LIST = "UPDATE_CUSTOMER_LIST";
export const GET_CUSTOMER_LIST = "GET_CUSTOMER_LIST";
export const ADD_CUSTOMER_COMPLETE = "ADD_CUSTOMER_COMPLETE";
export const ADD_CUSTOMER = "ADD_CUSTOMER";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";

//api URI
export const GET_CUSTOMER_URI = "/getCustomers";
export const ADD_CUSTOMER_URI = "/addCustomer";
export const UPDATE_CUSTOMER_URI = "/updateCustomer";
export const DELETE_CUSTOMER_URI = "/deleteCustomer";
