
export const SET_ZONE_ID = "SET_ZONE_ID";
export const UPDATE_ZONE_LIST = "H_UPDATE_ZONE_LIST";
export const CHANGE_LIST_PAGE = "CHANGE_LIST_PAGE";
export const UPDATE_AFTER_SEARCH = "UPDATE_AFTER_SEARCH";
