//Actions
export const USER_NAME_CHANGE = "USER_NAME_CHANGE";
export const PASSWORD_CHANGE = "PASSWORD_CHANGE";
export const APPLICATION_LOGIN = "APPLICATION_LOGIN";
export const APPLICATION_LOGOUT = "APPLICATION_LOGOUT";

//Variables
export const USER_NAME = "USER_NAME";
export const PASSWORD = "PASSWORD";
